id: P5B16B968
initial_creation_type: input
source_metadata:
  title: Vasubandhu
  language: bo
  description: 'Texts by and about the great Indian paṇḍita Vasubandhu (dbyig gnyen),
    author of the Treasury of Abhidharma and other treatises:'
  volume:
    daa3a088284b4a109c4815cece61f80a:
      title: 'Light on the Path of Liberation: The Life of the Second Buddha Vasubandhu'
      parent: Biography
    b484d7d60ec64c5db3840b931cbe0f4c:
      title: In Praise of the Three Jewels
      parent: Praise
created_at: '2022-03-01T02:26:39.735030'
last_modified_at: '2022-03-01T02:26:39.735034'
statistics:
  total_words: 1287
  total_non_words: 99
quality:
  non_words_ratio: 0.08
